### ISSUE TITLE
BatchedEngine incompatible with mlx-lm 0.31+ (BatchGenerator API changes)

### ISSUE THREAD

**Issue by raullenchai** [raullenchai/vllm-mlx#105]
## Problem

BatchedEngine and Scheduler fail with recent mlx-lm versions (0.31+) due to two API breaking changes in `mlx_lm.generate`:

### 1. `BatchGenerator.__init__()` no longer accepts `prompt_progress_callback`

```
TypeError: BatchGenerator.__init__() got an unexpected keyword argument 'prompt_progress_callback'
```

**Location**: `vllm_mlx/scheduler.py:1176`
**Fix**: Already applied locally — removed the parameter. The prefill progress logging callback was our custom addition that mlx-lm removed.

### 2. `Batch` class removed from `mlx_lm.generate`

```
ImportError: cannot import name 'Batch' from 'mlx_lm.generate'
```

**Location**: `vllm_mlx/scheduler.py:157` (in `_install_chunked_prefill`)
**Fix needed**: The chunked prefill implementation imports `Batch` which no longer exists in mlx-lm. This requires adapting to the new mlx-lm chunked prefill API.

## Impact

- **8 test failures** across `test_batching_deterministic.py`, `test_continuous_batching.py`, and `test_model_registry.py`
- All failures are in `BatchedEngine` (continuous batching mode)
- **SimpleEngine (default mode) is unaffected** — all 2004+ SimpleEngine tests pass
- Users running `rapid-mlx serve <model>` (simple mode) are not impacted

## Current mlx-lm `BatchGenerator` signature

```python
BatchGenerator.__init__(self, model, max_tokens, stop_tokens, sampler,
                        logits_processors, completion_batch_size,
                        prefill_batch_size, prefill_step_size, max_kv_size)
```

## Steps to reproduce

```bash
pip install mlx-lm>=0.31
python3 -m pytest tests/test_batching_deterministic.py -v
```

## Proposed fix

1. ✅ Remove `prompt_progress_callback` from `BatchGenerator()` call (done)
2. Adapt `_install_chunked_prefill()` to work without `Batch` import — either:
   - Use mlx-lm's built-in chunked prefill (if available in 0.31+)
   - Reimplement chunking using the new API
3. Update any other `BatchGenerator` usage to match new signature

## Environment

- mlx-lm: 0.31.1
- mlx: 0.29.1
- Python: 3.12
- macOS: Darwin 25.3.0

**Comment by raullenchai** [comment]
Partially addressed in #106: removed `prompt_progress_callback` from `BatchGenerator()` call. The deeper `Batch` import issue remains.

**Comment by raullenchai** [comment]
Related: PR #106 merged — fixes `prompt_progress_callback` (one of the two breaking changes). `Batch` import issue remains open.

**Comment by julien-tdx** [comment]
same problem here.
(just tried your fork as vllm-mlx have a badly formatted output with Qwen3.5 for agents, which you may have fixed)

**Comment by raullenchai** [comment]
Thanks for reporting @julien-tdx. The BatchedEngine (`--continuous-batching`) is broken with mlx-lm 0.31+ due to the removed `Batch` class. 

**Workaround**: Run without `--continuous-batching` — SimpleEngine works perfectly:
```bash
rapid-mlx serve qwen3.5-9b
```

Regarding badly formatted output with Qwen3.5 for agents — can you share which agent you're using and what the malformed output looks like? We recently fixed several tool calling issues (PR #106, #111) that may address this.

Working on a proper fix for the BatchedEngine issue now.

**Comment by julien-tdx** [comment]
Thanks I will try without `--continuous-batching`

Using openclaw and vllm-mlx: 
- if I use `--tool-call-parser auto  --enable-auto-tool-choice` (I think auto will detect qwen3 automatically), tool_calls work, but the output is condensed: all linebreaks are striped making it hard to read.
- if I remove those flags, tool_calls do not work, but requests that do not require tool_calls are properly formatted with linebreaks etc

I heard about your fork which may have fixed that problem, thought I'd give it a go

**Comment by julien-tdx** [comment]
Yup, it works without `--continuous-batching`, and your fork properly formats the output unlike vllm-mlx, thanks !

I'll daily drive your fork for my projects

**Comment by raullenchai** [comment]
Fixed in #112. `--continuous-batching` now works with mlx-lm 0.31+.

@julien-tdx please update to the latest version and try again:
```bash
pip install rapid-mlx @ git+https://github.com/raullenchai/Rapid-MLX.git
rapid-mlx serve qwen3.5-9b --continuous-batching
```

**Comment by julien-tdx** [comment]
@raullenchai it works with 0.5.0 thank you.

although I still have those errors in the logs:

```
ERROR:vllm_mlx.engine_core:Engine loop error: 'BatchGenerator' object has no attribute 'active_batch'
Traceback (most recent call last):
  File "/Users/user/.local/share/uv/tools/rapid-mlx/lib/python3.12/site-packages/vllm_mlx/engine_core.py", line 195, in _engine_loop
    output = self.scheduler.step()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/share/uv/tools/rapid-mlx/lib/python3.12/site-packages/vllm_mlx/scheduler.py", line 2376, in step
    and self.batch_generator.active_batch is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BatchGenerator' object has no attribute 'active_batch'
```

and some file reading tool calling fail, but that may be unrelated
